SENSOR_CONFIG = {
    "heartrate": {
        "expected_interval_sec": 5,
        "gap_threshold_sec": 60,
        "unit": "bpm",
        "value_range": (30, 220),
        "aggregation": "mean",
        "display_bin_sec": 30,
    },
    "vibration": {
        "expected_interval_sec": 0.002,  # 500 Hz
        "gap_threshold_sec": 5,
        "unit": "adc_counts",
        "value_range": None,
        "aggregation": "rms",
        "display_bin_sec": 1,
    },

    # these are all placeholders until we get real data 
    "motion": {
        "expected_interval_sec": 30,
        "gap_threshold_sec": 300,
        "unit": "binary",
        "value_range": (0, 1),
        "aggregation": "max",
        "display_bin_sec": 60,
    },
    "bed_sensor": {
        "expected_interval_sec": 60,
        "gap_threshold_sec": 600,
        "unit": "binary",
        "value_range": (0, 1),
        "aggregation": "max",
        "display_bin_sec": 120,
    },
    "light_temperature": {
        "expected_interval_sec": 60,
        "gap_threshold_sec": 600,
        "unit": "lux_or_celsius",  # split rows by sensor_id suffix
        "value_range": None,
        "aggregation": "mean",
        "display_bin_sec": 60,
    },
    "wearable_light": {
        "expected_interval_sec": 30,
        "gap_threshold_sec": 300,
        "unit": "lux",
        "value_range": (0, None),
        "aggregation": "mean",
        "display_bin_sec": 60,
    },
    "pressure": {
        "expected_interval_sec": 60,
        "gap_threshold_sec": 600,
        "unit": "Pa",
        "value_range": None,
        "aggregation": "mean",
        "display_bin_sec": 120,
    },
    "surface_temperature": {
        "expected_interval_sec": 60,
        "gap_threshold_sec": 600,
        "unit": "celsius",
        "value_range": None,
        "aggregation": "mean",
        "display_bin_sec": 60,
    },
    "smart_plug": {
        "expected_interval_sec": 60,
        "gap_threshold_sec": 600,
        "unit": "binary",
        "value_range": (0, 1),
        "aggregation": "binary",
        "display_bin_sec": 60,
    },
    "depth_camera": {
        "expected_interval_sec": 30,
        "gap_threshold_sec": 300,
        "unit": "events",
        "value_range": (0, None),
        "aggregation": "max",
        "display_bin_sec": 60,
    },

    # Empatica Embrace Plus — digital_biomarkers/aggregated_per_minute/
    # All signals arrive at 1-per-minute. signal_col identifies the CSV value column.
    # source_file is the suffix used in the filename (e.g. *_pulse-rate.csv).
    # absent_means_not_wearing: NaN rows come from missing_value_reason in the CSV,
    # which for a wearable means the participant wasn't wearing the device — not a
    # sensor fault. gap_detector surfaces these as "not wearing" rather than data gaps.
    "empatica_pulse_rate": {
        "expected_interval_sec": 60,
        "gap_threshold_sec": 300,
        "unit": "bpm",
        "value_range": (30, 220),
        "aggregation": "mean",
        "display_bin_sec": 60,
        "signal_col": "pulse_rate_bpm",
        "source_file": "pulse-rate",
        "absent_means_not_wearing": True,
    },
    "empatica_temperature": {
        "expected_interval_sec": 60,
        "gap_threshold_sec": 300,
        "unit": "celsius",
        "value_range": (20, 45),
        "aggregation": "mean",
        "display_bin_sec": 60,
        "signal_col": "temperature_celsius",
        "source_file": "temperature",
        "absent_means_not_wearing": True,
    },
    "empatica_wearing_detection": {
        "expected_interval_sec": 60,
        "gap_threshold_sec": 300,
        "unit": "percent",
        "value_range": (0, 100),
        "aggregation": "mean",
        "display_bin_sec": 60,
        "signal_col": "wearing_detection_percentage",
        "source_file": "wearing-detection",
        "absent_means_not_wearing": True,
    },
    "empatica_eda": {
        "expected_interval_sec": 60,
        "gap_threshold_sec": 300,
        "unit": "uSiemens",
        "value_range": (0, None),
        "aggregation": "mean",
        "display_bin_sec": 60,
        "signal_col": "eda_scl_usiemens",
        "source_file": "eda",
        "absent_means_not_wearing": True,
    },
    "empatica_prv": {
        "expected_interval_sec": 60,
        "gap_threshold_sec": 300,
        "unit": "ms",
        "value_range": (0, None),
        "aggregation": "mean",
        "display_bin_sec": 60,
        "signal_col": "prv_rmssd_ms",
        "source_file": "prv",
        "absent_means_not_wearing": True,
    },
    "empatica_respiratory_rate": {
        "expected_interval_sec": 60,
        "gap_threshold_sec": 300,
        "unit": "brpm",
        "value_range": (0, None),
        "aggregation": "mean",
        "display_bin_sec": 60,
        "signal_col": "respiratory_rate_brpm",
        "source_file": "respiratory-rate",
        "absent_means_not_wearing": True,
    },
    "empatica_step_counts": {
        "expected_interval_sec": 60,
        "gap_threshold_sec": 300,
        "unit": "steps",
        "value_range": (0, None),
        "aggregation": "sum",
        "display_bin_sec": 60,
        "signal_col": "step_counts",
        "source_file": "step-counts",
        "absent_means_not_wearing": True,
    },
    "empatica_met": {
        "expected_interval_sec": 60,
        "gap_threshold_sec": 300,
        "unit": "METs",
        "value_range": (0, None),
        "aggregation": "mean",
        "display_bin_sec": 60,
        "signal_col": "met",
        "source_file": "met",
        "absent_means_not_wearing": True,
    },
    "empatica_activity_counts": {
        "expected_interval_sec": 60,
        "gap_threshold_sec": 300,
        "unit": "counts",
        "value_range": (0, None),
        "aggregation": "sum",
        "display_bin_sec": 60,
        "signal_col": "activity_counts",
        "source_file": "activity-counts",
        "absent_means_not_wearing": True,
    },
    "empatica_accelerometers_std": {
        "expected_interval_sec": 60,
        "gap_threshold_sec": 300,
        "unit": "g",
        "value_range": (0, None),
        "aggregation": "mean",
        "display_bin_sec": 60,
        "signal_col": "accelerometers_std_g",
        "source_file": "accelerometers-std",
        "absent_means_not_wearing": True,
    },
    "empatica_sleep_detection": {
        "expected_interval_sec": 60,
        "gap_threshold_sec": 300,
        "unit": "stage",
        "value_range": None,
        "aggregation": "max",
        "display_bin_sec": 60,
        "signal_col": "sleep_detection_stage",
        "source_file": "sleep-detection",
        "absent_means_not_wearing": True,
    },
    "empatica_actigraphy_counts": {
        "expected_interval_sec": 60,
        "gap_threshold_sec": 300,
        "unit": "counts",
        "value_range": (0, None),
        "aggregation": "sum",
        "display_bin_sec": 60,
        "signal_col": "vector_magnitude",
        "source_file": "actigraphy-counts",
        "absent_means_not_wearing": True,
    },
    "empatica_acticounts": {
        "expected_interval_sec": 60,
        "gap_threshold_sec": 300,
        "unit": "counts",
        "value_range": (0, None),
        "aggregation": "sum",
        "display_bin_sec": 60,
        "signal_col": "acticounts_y_axis",   # y-axis (vertical) as representative; all axes share identical gaps
        "source_file": "acticounts",
        "absent_means_not_wearing": True,
    },
    "empatica_activity_classification": {
        "expected_interval_sec": 60,
        "gap_threshold_sec": 300,
        "unit": "class",
        "value_range": None,
        "aggregation": "max",
        "display_bin_sec": 60,
        "signal_col": "activity_class",
        "source_file": "activity-classification",
        "absent_means_not_wearing": True,
    },
    "empatica_activity_intensity": {
        "expected_interval_sec": 60,
        "gap_threshold_sec": 300,
        "unit": "intensity",
        "value_range": (0, None),
        "aggregation": "mean",
        "display_bin_sec": 60,
        "signal_col": "activity_intensity",
        "source_file": "activity-intensity",
        "absent_means_not_wearing": True,
    },
    "empatica_body_position": {
        "expected_interval_sec": 60,
        "gap_threshold_sec": 300,
        "unit": "position",
        "value_range": None,
        "aggregation": "max",
        "display_bin_sec": 60,
        "signal_col": "body_position_left",  # left side as representative; both sides share identical gaps
        "source_file": "body-position",
        "absent_means_not_wearing": True,
    },
}
